import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Activity, BarChart3, Bot, ChevronRight, CircleUserRound, DoorOpen, Gauge, LogOut, RefreshCw, Search, ShieldCheck, Swords, Trophy, Users, UserRoundCog, X } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { adminApi, type AdminUser } from "@/lib/admin-api";

export const Route = createFileRoute("/dashboard-raees")({ component: AdminDashboard });

type Tab = "overview" | "users" | "matches" | "rooms" | "rankings" | "analytics" | "activity";
const tabs: Array<{ id: Tab; label: string; icon: typeof Gauge }> = [
  { id: "overview", label: "Overview", icon: Gauge }, { id: "users", label: "Users", icon: Users }, { id: "matches", label: "Matches", icon: Swords },
  { id: "rooms", label: "Live rooms", icon: DoorOpen }, { id: "rankings", label: "Rankings", icon: Trophy }, { id: "analytics", label: "Analytics", icon: BarChart3 }, { id: "activity", label: "Audit log", icon: Activity },
];
const number = new Intl.NumberFormat("en-US");
const date = (value: string | null | undefined) => value ? new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" }) : "Never";

function AdminDashboard() {
  const [admin, setAdmin] = useState<{ username: string } | null>(null);
  const [checking, setChecking] = useState(true);
  const [tab, setTab] = useState<Tab>("overview");
  const [loginError, setLoginError] = useState("");
  const [refreshing, setRefreshing] = useState(false);
  const [data, setData] = useState<any>({ stats: {}, users: [], matches: [], rooms: [], growth: [], visits: [], dailyMatches: [], split: [], activity: [] });

  async function load() {
    setRefreshing(true);
    try { const [overview, users, matches, rooms, analytics, activity] = await Promise.all([adminApi.overview(), adminApi.users(), adminApi.matches(), adminApi.rooms(), adminApi.analytics(), adminApi.activity()]); setData({ ...overview, ...users, ...matches, ...rooms, ...analytics, ...activity }); } catch (error) { if (error instanceof Error && error.message.includes("authentication")) setAdmin(null); } finally { setRefreshing(false); }
  }
  useEffect(() => { adminApi.session().then((result) => { setAdmin(result.admin); }).catch(() => {}).finally(() => setChecking(false)); }, []);
  useEffect(() => { if (admin) void load(); }, [admin]);
  if (checking) return <div className="admin-loading">Checking secure admin session...</div>;
  if (!admin) return <AdminLogin onLogin={setAdmin} error={loginError} setError={setLoginError} />;
  const stats = data.stats as Record<string, number>;
  return <div className="admin-shell">
    <aside className="admin-sidebar">
      <div className="admin-brand"><span className="admin-brand-mark"><ShieldCheck size={22} /></span><span><strong>WallRush</strong><small>Control center</small></span></div>
      <div className="admin-secure"><span className="admin-live-dot" /> Private admin mode</div>
      <nav className="admin-nav">{tabs.map(({ id, label, icon: Icon }) => <button key={id} className={tab === id ? "active" : ""} onClick={() => setTab(id)}><Icon size={17} />{label}{id === "rooms" && stats["activeRooms"] ? <b>{stats["activeRooms"]}</b> : null}</button>)}</nav>
      <div className="admin-sidebar-foot"><div className="admin-identity"><CircleUserRound size={30} /><span><strong>{admin.username}</strong><small>Administrator</small></span></div><button className="admin-logout" onClick={() => { void adminApi.logout().finally(() => setAdmin(null)); }}><LogOut size={16} /> Sign out</button></div>
    </aside>
    <main className="admin-main">
      <header className="admin-topbar"><div><p className="admin-eyebrow">WallRush / Administration</p><h1>{tabs.find((item) => item.id === tab)?.label}</h1></div><button className="admin-refresh" onClick={() => void load()} disabled={refreshing}><RefreshCw size={16} className={refreshing ? "spin" : ""} /> {refreshing ? "Refreshing" : "Refresh data"}</button></header>
      {tab === "overview" && <Overview stats={stats} />}
      {tab === "users" && <UsersPanel users={data.users} onReload={load} />}
      {tab === "matches" && <MatchesPanel matches={data.matches} />}
      {tab === "rooms" && <RoomsPanel rooms={data.rooms} />}
      {tab === "rankings" && <RankingsPanel users={data.users} />}
      {tab === "analytics" && <AnalyticsPanel data={data} />}
      {tab === "activity" && <ActivityPanel activity={data.activity} />}
    </main>
  </div>;
}

function AdminLogin({ onLogin, error, setError }: { onLogin: (admin: { username: string }) => void; error: string; setError: (value: string) => void }) {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setBusy(true); setError(""); try { const result = await adminApi.login(username, password); onLogin(result.admin); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to sign in"); } finally { setBusy(false); } }
  return <div className="admin-login-page"><div className="admin-login-glow" /><form className="admin-login-card" onSubmit={submit}><div className="admin-login-icon"><ShieldCheck size={30} /></div><p className="admin-eyebrow">Restricted access</p><h1>Admin command center</h1><p className="admin-login-copy">Sign in with your private administrator credentials to continue.</p><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoComplete="username" required /></label><label>Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete="current-password" required /></label>{error && <p className="admin-error">{error}</p>}<button className="admin-primary" disabled={busy}>{busy ? "Authenticating..." : "Enter dashboard"}<ChevronRight size={17} /></button><small className="admin-login-note">Protected by server-side session authorization</small></form></div>;
}

function Overview({ stats }: { stats: Record<string, number> }) {
  const cards = [{ label: "Registered users", key: "users", icon: Users, tone: "blue" }, { label: "Online now", key: "online", icon: Activity, tone: "green" }, { label: "Total matches", key: "matches", icon: Swords, tone: "orange" }, { label: "Points distributed", key: "points", icon: Trophy, tone: "purple" }];
  const secondary = [{ label: "Visitors today", key: "visitorsToday" }, { label: "Visitors this week", key: "visitorsWeek" }, { label: "Visitors this month", key: "visitorsMonth" }, { label: "Total visitors", key: "visitors" }, { label: "Active rooms", key: "activeRooms" }, { label: "Waiting rooms", key: "waitingRooms" }, { label: "Real-player matches", key: "realMatches" }, { label: "Bot matches", key: "botMatches" }, { label: "New users today", key: "newToday" }, { label: "New users this week", key: "newWeek" }, { label: "New users this month", key: "newMonth" }, { label: "Completed matches", key: "matches" }];
  return <><section className="admin-kpi-grid">{cards.map(({ label, key, icon: Icon, tone }) => <div className={`admin-kpi ${tone}`} key={key}><span className="admin-kpi-icon"><Icon size={20} /></span><small>{label}</small><strong>{number.format(stats[key] ?? 0)}</strong><span className="admin-kpi-caption">Live Neon data</span></div>)}</section><section className="admin-section"><div className="admin-section-head"><div><p className="admin-eyebrow">System pulse</p><h2>Operational snapshot</h2></div><span className="admin-status-pill"><span className="admin-live-dot" /> Live</span></div><div className="admin-stat-grid">{secondary.map(({ label, key }) => <div className="admin-stat" key={key}><span>{label}</span><strong>{number.format(stats[key] ?? 0)}</strong></div>)}</div></section><section className="admin-insight-grid"><div className="admin-insight"><Bot size={20} /><div><strong>Bot matches stay unranked</strong><p>AI opponents are tracked separately and never change human leaderboards.</p></div></div><div className="admin-insight"><UserRoundCog size={20} /><div><strong>Protected operations</strong><p>Every account change is authorized server-side and written to the audit log.</p></div></div></section></>;
}

function UsersPanel({ users, onReload }: { users: AdminUser[]; onReload: () => Promise<void> }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<AdminUser | null>(null); const [saving, setSaving] = useState(false); const visible = useMemo(() => users.filter((user) => `${user.username} ${user.email}`.toLowerCase().includes(query.toLowerCase())), [users, query]);
  async function save(changes: Record<string, unknown>) { if (!selected) return; setSaving(true); try { await adminApi.updateUser(selected.id, changes); await onReload(); const refreshed = await adminApi.user(selected.id); setSelected(refreshed.user); } finally { setSaving(false); } }
  return <div className="admin-section"><div className="admin-section-head"><div><p className="admin-eyebrow">Directory</p><h2>User management</h2></div><span className="admin-count">{visible.length} users</span></div><div className="admin-toolbar"><div className="admin-search"><Search size={17} /><input placeholder="Search by username or email" value={query} onChange={(event) => setQuery(event.target.value)} /></div></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>User</th><th>Status</th><th>Points</th><th>Record</th><th>Created</th><th /></tr></thead><tbody>{visible.map((user) => <tr key={user.id}><td><strong>{user.username}</strong><small>{user.email}</small></td><td><span className={`admin-badge ${user.disabled ? "red" : "green"}`}>{user.disabled ? "Disabled" : "Active"}</span></td><td>{number.format(user.points)}</td><td>{user.wins}W / {user.losses}L</td><td>{date(user.created_at)}</td><td><button className="admin-icon-button" onClick={() => setSelected(user)}><ChevronRight size={17} /></button></td></tr>)}</tbody></table></div>{selected && <UserDrawer user={selected} onClose={() => setSelected(null)} onSave={save} saving={saving} />}</div>;
}

function UserDrawer({ user, onClose, onSave, saving }: { user: AdminUser; onClose: () => void; onSave: (changes: Record<string, unknown>) => Promise<void>; saving: boolean }) {
  const [username, setUsername] = useState(user.username); const [points, setPoints] = useState(String(user.points)); const [wins, setWins] = useState(String(user.wins)); const [losses, setLosses] = useState(String(user.losses)); const [disabled, setDisabled] = useState(user.disabled); const [password, setPassword] = useState("");
  return <div className="admin-drawer-backdrop" onClick={onClose}><aside className="admin-drawer" onClick={(event) => event.stopPropagation()}><div className="admin-drawer-head"><div><p className="admin-eyebrow">User profile</p><h2>{user.username}</h2></div><button className="admin-icon-button" onClick={onClose}><X size={18} /></button></div><div className="admin-profile-summary"><CircleUserRound size={38} /><div><strong>{user.email}</strong><span>Rank #{user.rank ?? "-"} · {user.match_count ?? user.games} matches</span></div></div><div className="admin-form-grid"><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} /></label><label>Points<input type="number" value={points} onChange={(event) => setPoints(event.target.value)} /></label><label>Wins<input type="number" value={wins} onChange={(event) => setWins(event.target.value)} /></label><label>Losses<input type="number" value={losses} onChange={(event) => setLosses(event.target.value)} /></label><label className="wide">Reset password<input type="password" placeholder="Leave blank to keep current" value={password} onChange={(event) => setPassword(event.target.value)} /></label></div><label className="admin-toggle"><input type="checkbox" checked={disabled} onChange={(event) => setDisabled(event.target.checked)} /> Disable account</label><div className="admin-drawer-actions"><button className="admin-secondary" onClick={onClose}>Cancel</button><button className="admin-primary" disabled={saving} onClick={() => void onSave({ username, points: Number(points), wins: Number(wins), losses: Number(losses), disabled, ...(password ? { password } : {}) })}>{saving ? "Saving..." : "Save changes"}</button></div></aside></div>;
}

function MatchesPanel({ matches }: { matches: any[] }) { return <TableSection eyebrow="Game operations" title="Match management" count={`${matches.length} records`}><table className="admin-table"><thead><tr><th>Match</th><th>Player</th><th>Opponent</th><th>Result</th><th>Points</th><th>Recorded</th></tr></thead><tbody>{matches.map((match) => <tr key={match.id}><td><code>{String(match.id).slice(0, 8)}</code></td><td><strong>{match.username}</strong></td><td><span className="admin-badge blue">{match.opponent_type === "ai" ? "AI bot" : "Real player"}</span><small>{match.opponent_name ?? "-"}</small></td><td><span className={`admin-badge ${match.result === "win" ? "green" : "red"}`}>{match.result}</span></td><td>{match.points}</td><td>{date(match.created_at)}</td></tr>)}</tbody></table></TableSection>; }
function RoomsPanel({ rooms }: { rooms: any[] }) { return <TableSection eyebrow="Live operations" title="Room monitor" count={`${rooms.length} rooms`}><table className="admin-table"><thead><tr><th>Room</th><th>Players</th><th>Mode</th><th>Status</th><th>Last activity</th></tr></thead><tbody>{rooms.map((room) => <tr key={room.id}><td><strong>{room.code}</strong></td><td>{room.p1_name ?? "-"} <span className="admin-muted">vs</span> {room.p2_name ?? "Waiting"}</td><td>{room.is_bot ? <span className="admin-badge purple">Bot match</span> : <span className="admin-badge blue">Human</span>}</td><td><span className={`admin-badge ${room.status === "playing" ? "green" : "orange"}`}>{room.status}</span></td><td>{date(room.updated_at)}</td></tr>)}</tbody></table></TableSection>; }
function RankingsPanel({ users }: { users: AdminUser[] }) { return <TableSection eyebrow="Leaderboard" title="Ranking management" count={`${users.length} ranked users`}><table className="admin-table"><thead><tr><th>Rank</th><th>Username</th><th>Points</th><th>Wins</th><th>Losses</th><th>Win rate</th><th>Status</th></tr></thead><tbody>{[...users].sort((a, b) => b.points - a.points).map((user, index) => <tr key={user.id}><td><strong>#{index + 1}</strong></td><td>{user.username}</td><td>{number.format(user.points)}</td><td>{user.wins}</td><td>{user.losses}</td><td>{user.games ? `${Math.round(user.wins / user.games * 100)}%` : "0%"}</td><td>{user.disabled ? "Disabled" : "Active"}</td></tr>)}</tbody></table></TableSection>; }
function AnalyticsPanel({ data }: { data: any }) { const growth = data.growth.map((item: any) => ({ day: String(item.day).slice(5), users: item.count })); const visits = data.visits.map((item: any) => ({ day: String(item.day).slice(5), visitors: item.count })); const matches = data.dailyMatches.map((item: any) => ({ day: String(item.day).slice(5), matches: item.count })); return <div className="admin-chart-grid"><Chart title="User growth" data={growth} keys={["users"]} colors={["#58a6ff"]} /><Chart title="Daily visitors" data={visits} keys={["visitors"]} colors={["#51d88a"]} /><Chart title="Matches per day" data={matches} keys={["matches"]} colors={["#ffb454"]} /><div className="admin-chart-card"><h3>Match composition</h3><ResponsiveContainer width="100%" height={235}><BarChart data={data.split}><CartesianGrid strokeDasharray="3 3" stroke="#26364b" /><XAxis dataKey="type" stroke="#8da0b8" /><YAxis stroke="#8da0b8" /><Tooltip /><Bar dataKey="count" fill="#a78bfa" radius={[5, 5, 0, 0]} /></BarChart></ResponsiveContainer></div></div>; }
function Chart({ title, data, keys, colors }: { title: string; data: any[]; keys: string[]; colors: string[] }) { return <div className="admin-chart-card"><h3>{title}</h3><ResponsiveContainer width="100%" height={235}><AreaChart data={data}><defs>{keys.map((key, index) => <linearGradient key={key} id={`gradient-${key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor={colors[index]} stopOpacity={0.35} /><stop offset="95%" stopColor={colors[index]} stopOpacity={0} /></linearGradient>)}</defs><CartesianGrid strokeDasharray="3 3" stroke="#26364b" /><XAxis dataKey="day" stroke="#8da0b8" /><YAxis stroke="#8da0b8" allowDecimals={false} /><Tooltip /><Legend />{keys.map((key, index) => <Area key={key} type="monotone" dataKey={key} stroke={colors[index]} fill={`url(#gradient-${key})`} strokeWidth={2} />)}</AreaChart></ResponsiveContainer></div>; }
function ActivityPanel({ activity }: { activity: any[] }) { return <TableSection eyebrow="Security trail" title="Admin activity log" count={`${activity.length} events`}><table className="admin-table"><thead><tr><th>Action</th><th>Actor</th><th>Target</th><th>Details</th><th>Timestamp</th></tr></thead><tbody>{activity.map((item) => <tr key={item.id}><td><span className="admin-badge blue">{item.action}</span></td><td>{item.actor}</td><td><code>{item.target_id ? String(item.target_id).slice(0, 8) : "-"}</code></td><td className="admin-muted">{JSON.stringify(item.details)}</td><td>{date(item.created_at)}</td></tr>)}</tbody></table></TableSection>; }
function TableSection({ eyebrow, title, count, children }: { eyebrow: string; title: string; count: string; children: React.ReactNode }) { return <section className="admin-section"><div className="admin-section-head"><div><p className="admin-eyebrow">{eyebrow}</p><h2>{title}</h2></div><span className="admin-count">{count}</span></div><div className="admin-table-wrap">{children}</div></section>; }
