/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvertiseRouteImport } from './routes/advertise'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRaeesRouteImport } from './routes/dashboard-raees'
import { Route as FriendRouteImport } from './routes/friend'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RulesRouteImport } from './routes/rules'
import { Route as SupportRouteImport } from './routes/support'
import { Route as RoomCodeRouteImport } from './routes/room.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertiseRoute = AdvertiseRouteImport.update({
  id: '/advertise',
  path: '/advertise',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRaeesRoute = DashboardRaeesRouteImport.update({
  id: '/dashboard-raees',
  path: '/dashboard-raees',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendRoute = FriendRouteImport.update({
  id: '/friend',
  path: '/friend',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RulesRoute = RulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomCodeRoute = RoomCodeRouteImport.update({
  id: '/room/$code',
  path: '/room/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard-raees': typeof DashboardRaeesRoute
  '/friend': typeof FriendRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/support': typeof SupportRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard-raees': typeof DashboardRaeesRoute
  '/friend': typeof FriendRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/support': typeof SupportRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advertise': typeof AdvertiseRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard-raees': typeof DashboardRaeesRoute
  '/friend': typeof FriendRoute
  '/online': typeof OnlineRoute
  '/profile': typeof ProfileRoute
  '/ranking': typeof RankingRoute
  '/reviews': typeof ReviewsRoute
  '/rules': typeof RulesRoute
  '/support': typeof SupportRoute
  '/room/$code': typeof RoomCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advertise'
    | '/ai'
    | '/auth'
    | '/dashboard-raees'
    | '/friend'
    | '/online'
    | '/profile'
    | '/ranking'
    | '/reviews'
    | '/rules'
    | '/support'
    | '/room/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advertise'
    | '/ai'
    | '/auth'
    | '/dashboard-raees'
    | '/friend'
    | '/online'
    | '/profile'
    | '/ranking'
    | '/reviews'
    | '/rules'
    | '/support'
    | '/room/$code'
  id:
    | '__root__'
    | '/'
    | '/advertise'
    | '/ai'
    | '/auth'
    | '/dashboard-raees'
    | '/friend'
    | '/online'
    | '/profile'
    | '/ranking'
    | '/reviews'
    | '/rules'
    | '/support'
    | '/room/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvertiseRoute: typeof AdvertiseRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  DashboardRaeesRoute: typeof DashboardRaeesRoute
  FriendRoute: typeof FriendRoute
  OnlineRoute: typeof OnlineRoute
  ProfileRoute: typeof ProfileRoute
  RankingRoute: typeof RankingRoute
  ReviewsRoute: typeof ReviewsRoute
  RulesRoute: typeof RulesRoute
  SupportRoute: typeof SupportRoute
  RoomCodeRoute: typeof RoomCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertise': {
      id: '/advertise'
      path: '/advertise'
      fullPath: '/advertise'
      preLoaderRoute: typeof AdvertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard-raees': {
      id: '/dashboard-raees'
      path: '/dashboard-raees'
      fullPath: '/dashboard-raees'
      preLoaderRoute: typeof DashboardRaeesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend': {
      id: '/friend'
      path: '/friend'
      fullPath: '/friend'
      preLoaderRoute: typeof FriendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rules': {
      id: '/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$code': {
      id: '/room/$code'
      path: '/room/$code'
      fullPath: '/room/$code'
      preLoaderRoute: typeof RoomCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvertiseRoute: AdvertiseRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  DashboardRaeesRoute: DashboardRaeesRoute,
  FriendRoute: FriendRoute,
  OnlineRoute: OnlineRoute,
  ProfileRoute: ProfileRoute,
  RankingRoute: RankingRoute,
  ReviewsRoute: ReviewsRoute,
  RulesRoute: RulesRoute,
  SupportRoute: SupportRoute,
  RoomCodeRoute: RoomCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
